### ISSUE TITLE
Version bumping

### ISSUE THREAD

**Issue by mikaeltw** [aurany/ibmdb2-utils#1]
Could we try to make the plugin work with at least dbt version 1.2.1?

https://github.com/aurany/ibmdb2-utils/blob/1ef9f0a03bfec601a326b0e8cbbf79360f4e5e05/dbt_project.yml#L4

What is needed to support 1.2.1?

@aurany

**Comment by aurany** [comment]
@mikaeltw this is now fixed in 0.1.1. Utils will be moved to main repo (dbt-ibmdb2) soon when 0.2.0 is released.
